from django.urls import path
from .views import *

urlpatterns = [
    path('', landing_view, name='landing'),
    path('app/', board_view, name='home'), 
    path('roadmap/', roadmap_view, name='roadmap'),
    path('task/<int:task_id>/save/', saveView, name='save_task'),
    path('backlog/', backlog_view, name='backlog'),
    path('code/', code_view, name='code'),
    path('project-pages/', project_pages, name='projectpages'),
    path('members/', members, name='members'),
    path('time-tracking/', time_tracking, name='timetracking'),
    path('project-settings/', project_settings, name='projectsettings'),
    path('profile/', profile, name='profile'),
    path('onboard/', onboard, name="onboard"),
    path('join/', join_workspace, name='join_workspace'),
    path('workspace/<int:workspace_id>/switch/', switch_workspace, name='switch_workspace'),
    path('code/connect/', save_github_repo, name="save_github_repo"),
    path('code/disconnect/', disconnect_github_repo, name="disconnect_github_repo"),
    path('code/github/repo/', github_repo_api, name='github_repo_api'),
    path('code/github', github_repo_api, name='github_repo_api_base'),
    path('code/github/commits/', github_commits_api, name='github_commits_api'),
    path('code/github/commits', github_commits_api),
    path('code/github/branches/', github_branches_api, name='github_branches_api'),
    path('code/github/branches', github_branches_api),
    path('code/github/pulls/', github_pulls_api, name='github_pulls_api'),
    path('code/github/pulls', github_pulls_api),
    path('code/github/contributors/', github_contributors_api, name='github_contributors_api'),
    path('code/github/contributors', github_contributors_api),
    path('code/github/contents/', github_contents_api, name='github_contents_api'),
    path('code/github/contents', github_contents_api),
    path('task/<int:task_id>/delete/', delete_task, name='delete_task'),
    path('create/', create_workspace, name='create_workspace'),
]
