# Generated by Django 4.2.30 on 2026-06-22 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubrepositoryconnection',
            name='user',
        ),
        migrations.AddField(
            model_name='githubrepositoryconnection',
            name='connected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='github_connections_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='githubrepositoryconnection',
            name='workspace',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='github_connection', to='projects.workspace'),
        ),
        migrations.DeleteModel(
            name='TimeEntry',
        ),
    ]
