# Generated by Django 4.2.30 on 2026-06-22 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_githubrepositoryconnection_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrepositoryconnection',
            name='workspace',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='github_connection', to='projects.workspace'),
            preserve_default=False,
        ),
    ]
