# Generated by Django 4.2.30 on 2026-06-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_createtask_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='createtask',
            name='in_backlog',
            field=models.BooleanField(default=True),
        ),
    ]
